from typing import Protocol

from vv.models import CartPayload, Request


class Provider(Protocol):
    def search(self, query: str, limit: int) -> dict: ...
    def get(self, product_id: int) -> dict: ...
    def analogs(self, product_id: int) -> dict: ...
    def refresh(self, request: Request) -> dict: ...
    def create_link(self, payload: CartPayload) -> str: ...
