from typing import Protocol

from vv.models import CartPayload, ProductSnapshot, Request


class Provider(Protocol):
    def search(self, query: str, limit: int, page: int = 1) -> dict: ...
    def health(self) -> dict: ...
    def get(self, product_id: int) -> dict: ...
    def analogs(self, product_id: int) -> dict: ...
    def refresh(self, request: Request) -> list[ProductSnapshot]: ...
    def create_link(self, payload: CartPayload) -> str: ...
