from typing import Protocol

from vv.models import CartPayload, ProductSnapshot, Request


class Provider(Protocol):
    def search(self, query: str, limit: int, page: int = 1) -> dict: ...
    def health(self) -> dict: ...
    def get(self, product_id: int) -> dict: ...
    def analogs(self, product_id: int) -> dict: ...
    def barcode(self, barcode: str) -> dict: ...
    def discounts(
        self, page: int = 1, sort: str = "popularity", kind: str = "card", vvonly: int = 1
    ) -> dict: ...
    def recipes(
        self, query: str = "", page: int = 1, sort: str = "popularity", **filters
    ) -> dict: ...
    def shops(self, page: int = 1, **filters) -> dict: ...
    def orders(self, page: int = 1) -> dict: ...
    def favorite(self) -> dict: ...
    def refresh(self, request: Request) -> list[ProductSnapshot]: ...
    def create_link(self, payload: CartPayload) -> str: ...
